### ISSUE TITLE
[FEATURE]:  sort report by starttime and endtime

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1068]
### Please describe your feature request

The `buildtest report` has a field `starttime` and `endtime` that records the timestamp when test was run. It can be useful for someone to filter test by date.

We use [datetime](https://docs.python.org/3/library/datetime.html) library for recording the timestamp
```
 ~/ buildtest rt --format starttime,endtime
                                           Report File: /global/u1/s/siddiq90/gitrepos/buildtest/var/report.json
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ starttime                                                                   ┃ endtime                                                                    ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 2022/05/31 09:32:20                                                         │ 2022/05/31 09:36:53                                                        │
├─────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────┤
│ 2022/05/31 09:41:26                                                         │ 2022/05/31 10:17:20                                                        │
├─────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────┤
│ 2022/06/01 18:36:17                                                         │ 2022/06/01 18:36:24                                                        │
├─────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────┤
│ 2022/06/01 18:38:55                                                         │ 2022/06/01 18:39:02                                                        │
├─────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────┤
│ 2022/06/01 18:36:17                                                         │ 2022/06/01 18:36:44                                                        │
├─────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────┤
│ 2022/06/01 18:38:55                                                         │ 2022/06/01 18:39:21                                                        │
└─────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────┘
```

First we would like to get some option such as `buildtest report --start` with short option `-s` which will filter by starttime. Let's say one wants to see all test filtered by 2022-01-01 they can do the following: `buildtest report -s 2022-01-01`. We can also include `--end` with short option `-e` which will use the endtime. If both `-s` and `-e` are specified we will filter out all records that dont' fall within start and end time.

If `-e` is specified by itself then we will retrieve all records where all records in `endtime` exceed value specified by `-e`. We should have some error checking on following
1. - [x] Invalid Time
2. - [x] If `--start` is greater than `--end`
3.  - [x] If `--end` is greater than [datetime.datetime.now()](https://docs.python.org/3/library/datetime.html#datetime.datetime.now)

- [x] Add options `--start` and `--end` in https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/__init__.py
- [x] Add support for this feature in https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/report.py
- [x] Add bash completion https://github.com/buildtesters/buildtest/blob/devel/bash_completion.sh
- [x] Add regression test in https://github.com/buildtesters/buildtest/blob/devel/tests/cli/test_report.py
- [x] Add documentation in https://buildtest.readthedocs.io/en/devel/gettingstarted/query_test_report.html
### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by Xiangs18** [comment]
Hi @shahzebsiddiqui, I want to double confirm on the following conditions:

![image](https://user-images.githubusercontent.com/22202096/172688788-1c2a7330-0ed0-4f5a-bbd1-caef90d4b5d3.png)

**Comment by shahzebsiddiqui** [comment]
@Xiangs18 that is correct. If you look at the for loop in https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/report.py#L340-L362 you can declare a new method lets say `filter_by_start_end` or whatever that takes the two input fields `--start` and `--end` and return a `True` or `False` and skip test (i.e `continue`) in for loop.
