### ISSUE TITLE
[FEATURE]: Show path to buildtest configuration file

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1099]
### Please describe your feature request

Right now we don't have a quick way to check path to configuration file used for buildtest.

One can specify path on command line `buildtest -c <config_path>`, the path can be set via `$BUILDTEST_CONFIGFILE`. Right now one needs to run `buildtest config validate`  which shows the file that is being validated

```
(buildtest)  ~/gitrepos/buildtest/ [devel] buildtest config validate
/global/u1/s/siddiq90/gitrepos/buildtest-nersc/config.yml is valid
```

For this feature we would like to have a subcommand just to show path to configuration file this could be `buildtest config path` which shows path regardless if file is valid. This option doesn't need any other options just running the command should resolve to path of configuration file.

- [x] Add a new subcommand via argparser in  https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/__init__.py
- [x] Add method and implement logic in https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/config.py
- [x] Complete bash completion https://github.com/buildtesters/buildtest/blob/devel/bash_completion.sh
- [x] Add regression test in https://github.com/buildtesters/buildtest/blob/devel/tests/cli/test_config.py
- [x] Add user documentation in https://github.com/buildtesters/buildtest/blob/devel/docs/features.rst
- [x] Update `buildtest help config` section https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/help.py 

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by Xiangs18** [comment]
<img width="1435" alt="Screen Shot 2022-06-16 at 4 04 35 PM" src="https://user-images.githubusercontent.com/22202096/174154930-90655c9e-0f5b-45b0-8c42-a9d71b7d598c.png">

**Comment by Xiangs18** [comment]
Hey @shahzebsiddiqui, a bug is detected in devel branch:
https://github.com/buildtesters/buildtest/blob/dbe9be3baac9d70f386e2374f6e0e6a979a18106/buildtest/cli/__init__.py#L245 I already fixed it in my current branch. Thank you!

**Comment by shahzebsiddiqui** [comment]
Thanks for catching bug
