### ISSUE TITLE
fix broken urls reported by urlchecker

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1103]
@JeffreyFG here is another issue.
According to https://github.com/buildtesters/buildtest/runs/6939580062?check_suite_focus=true we have the following urls broken. We should fix them

![Screen Shot 2022-06-17 at 12 43 55 PM](https://user-images.githubusercontent.com/12942230/174341250-bbfac515-b1b2-4b65-a8d8-46bd74097df4.png)
 
TODO:
- [x] Fix link in user documentation or update https://github.com/buildtesters/buildtest/blob/devel/.github/workflows/urlchecker.yml

**Comment by shahzebsiddiqui** [comment]
@JeffreyFG 

Please use this link
CDASH: https://www.cdash.org/
PBS Docs: https://community.altair.com/community?id=altair_product_documentation

**Comment by JeffreyFG** [comment]
I have created a pull request Issue-1103-BrokenLinks
