### ISSUE TITLE
[DOCS]: ModuleNotFoundError: No module named 'buildtest'

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1154]
### Documentation Link

https://buildtest.readthedocs.io/en/devel/contributing/regression_testing.html

### Issue Description

Apparently the documentation is not showing the help message properly. This documentation page can be found in https://github.com/buildtesters/buildtest/blob/devel/docs/contributing/regression_testing.rst file. It leads me to believe the `sys.path` is not setup properly however it should be working considering we have this set in `conf.py`

https://github.com/buildtesters/buildtest/blob/a3feb8637e5a138095d4c5f1f7b6e77084ad4eaa/docs/conf.py#L19-L20
 

```
$ python $BUILDTEST_ROOT/buildtest/tools/unittests.py --help
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/buildtest/tools/unittests.py", line 8, in <module>
    from buildtest.defaults import (
ModuleNotFoundError: No module named 'buildtest'
```

This command should work but it is not. The expected output should be 

```
(buildtest)  ~/Documents/github/buildtest/ [devel] python $BUILDTEST_ROOT/buildtest/tools/unittests.py --help
usage: unittest [-h] [-c] [-p PYTESTOPTS] [-s SOURCEFILES]

Run buildtest unit tests

optional arguments:
  -h, --help            show this help message and exit
  -c, --coverage        Enable coverage when running regression test
  -p PYTESTOPTS, --pytestopts PYTESTOPTS
                        Specify option to pytest
  -s SOURCEFILES, --sourcefiles SOURCEFILES
                        Specify path to file or directory when running
                        regression test

```

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by Xiangs18** [comment]
Hi @shahzebsiddiqui Mine is working. I cannot reproduce your error message. 

command: **python $BUILDTEST_ROOT/buildtest/tools/unittests.py --help**

<img width="788" alt="Screen Shot 2022-07-06 at 12 04 34 PM" src="https://user-images.githubusercontent.com/22202096/177594627-4061ccf5-17cd-4b59-aa34-19b7cffcef16.png">

**Comment by shahzebsiddiqui** [comment]
yes i know it works for me too it doesn't work in the readthedocs build. 

The only thing i can think of is add `sys.path.insert` to root of repo it is failing when importing the module but i dont get why it fails since the rest of docs is working. 

```
 sys.path.insert(0, here) 
```

The actual command is run with shell mode so it should understand `$BUILDTEST_ROOT`. This is documented in https://pythonhosted.org/sphinxcontrib-programoutput/#command-execution-and-shell-expansion

![Screen Shot 2022-07-06 at 4 27 25 PM](https://user-images.githubusercontent.com/12942230/177637074-6c19ae3f-145f-41c7-9a5b-ce04ed408a92.png)

**Comment by Xiangs18** [comment]
The rest of docs is working because they are code-block rather than command-output.
