### ISSUE TITLE
Spelling check CI

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1164]
Everyone makes spelling mistakes whether it's documentation, comments in code, etc...

In that case let's fix all of these. Found a githuv action https://github.com/marketplace/actions/run-pyspelling-as-a-github-action let's integrate this into the workflow

**Comment by Xiangs18** [comment]
The original spellcheck is probably a better alternative than fork repo:
https://github.com/marketplace/actions/github-spellcheck-action
