### ISSUE TITLE
Rich theme for standardizing colors

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1199]
We need to declare theme in one place that can be reused throughout throughout code base without updating all the styles

See https://rich.readthedocs.io/en/latest/style.html#loading-themes.

Let's start to declare a theme and slowly migrate part of the codebase to use the themes.

There are several tables used for the following commands:
- `buildtest build`
- `buildtest buildspec find`
- `buildtest buildspec invalid`
- `buildtest buildspec maintainers -l`
- `buildtest buildspec maintainers -b`
- `buildtest report`
- `buildtest report summary`
- `buildtest history list`
- `buildtest inspect list`

For the time being let's start to work on refactoring code for commands for the following commands:
-  `buildtest history list`, 
-  `buildtest inspect list`, 
- `buildtest buildspec maintainers -l`
- `buildtest buildspec maintainers -b`

**Comment by jscook2345** [comment]
I moved this here: https://github.com/orgs/buildtesters/projects/10
