### ISSUE TITLE
[FEATURE]: remove compilers dynamically via command line

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1201]
### Please describe your feature request

It would be nice to remove the compilers from command line via `buildtest config compilers rm <compiler>` to remove a compiler from the configuration file and update the configuration upon completion. This could be useful if one wants to remove an outdated compiler.

For instance `buildtest config compilers rm gcc_6.5.0` will remove a compiler name `gcc_6.5.0` which is the name of the compiler (entry in `buildtest cg compilers`)

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by jscook2345** [comment]
I think this issue should be in the next release milestone instead of SI

**Comment by shahzebsiddiqui** [comment]
okay i moved it over

**Comment by shahzebsiddiqui** [comment]
@Xiangs18 i think this task would be relevant to your past contributions such as `buildtest config compilers test`. With this one we can just focus on trying to remove the compilers by name. 

Another option i am thinking about clearing all the compilers but not sure about the command yet. For now if we can get this working that would be nice.

This feature can be useful to remove compilers that fail compiler testing. For example in https://buildtest.readthedocs.io/en/devel/configuring_buildtest/compilers.html#test-compilers-experimental-feature we show all the failed tests.
