### ISSUE TITLE
[FEATURE]: Add buildtest -helpcolor flag to

### ISSUE THREAD

**Issue by JeffreyFG** [buildtesters/buildtest#1206]
### Please describe your feature request

The amount of different colors can be confusing and it would before great if a use could have ``buildtest --helpcolor`` to find out which color options there are. 

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by shahzebsiddiqui** [comment]
This looks like a good request.

**Comment by shahzebsiddiqui** [comment]
@prathmesh4321 i am going to reassign this to you. I think we can print the output in a table something like https://rich.readthedocs.io/en/stable/appendix/colors.html. The output of each color can be standard black with background be the color of text that way each entry can be seen especially like `black` which may not work well in black terminal

That being said it would be something like

![Screen Shot 2022-09-30 at 3 33 25 PM](https://user-images.githubusercontent.com/12942230/193343604-f4075bd8-9b36-4ccb-b184-5feaf91ce721.png)
