### ISSUE TITLE
[FEATURE]: add pagination for 'buildtest inspect' command

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1210]
### Please describe your feature request

Let's add pagination support for **buildtest inspect** command that will be done via option `--pager` and short option `-p` to be consistent.

The pagination will be done via rich see https://rich.readthedocs.io/en/stable/console.html#paging. 

See related implementation in `buildtest report` or `buildtest buildspec` for pagination in files: https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/report.py and https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/buildspec.py  

# Action Item
- [x] Add `--pager` and `-p` option in https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/__init__.py 
- [x] Add support of pagination for commands `buildtest inspect buildspec`, `buildtest inspect name`, `buildtest inspect query` and `buildtest inspect list` in https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/inspect.py 
- [x] Add option to bash completion script https://github.com/buildtesters/buildtest/blob/devel/bash_completion.sh
- [x] Add regression test for pagination in https://github.com/buildtesters/buildtest/blob/devel/tests/cli/test_inspect.py
- [x] Add a row entry in `buildtest help inspect` pertaining to pagination in https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/help.py

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by jscook2345** [comment]
Why are we adding a pager instead of using the built-in ones for different shells?

**Comment by shahzebsiddiqui** [comment]
For a few reasons

1. Is to be consistent with other command options with pagination like `buildtest report --pager`, `buildtest buildspec --pager`
2. The [paging](https://rich.readthedocs.io/en/stable/console.html#paging) support in rich provides ability to paginate certain block of python code as pose paging the entire output of a command. I agree one could probably do the same thing with `buildtest <command> | more` to serve the same functionality.
3. Currently paging doesn't support colors but according to their docs one can preserve colors with `styles=True` in the [pager](https://rich.readthedocs.io/en/stable/reference/console.html#rich.console.Console.pager) class. This assumes that the Linux pager supports coloring, this is something i haven't explored but i'd like to enable paging with color as the default, i am pretty sure we are not doing this right now.
