### ISSUE TITLE
[FEATURE]: buildtest buildspec find --row-count

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1213]
### Please describe your feature request

The command `buildtest buildspec find --row-count` can be used to report the total count such as unique tags. This information is already captured but one needs to run `buildtest bc summary`

```
(buildtest)  ~/Documents/github/buildtest/ [color_changes_buildtest_hy] buildtest bc summary
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                           │
│     Reading Buildspec Cache File:   /Users/siddiq90/Documents/github/buildtest/var/buildspecs/cache.json  │
│     Total Valid Buildspecs:         48                                                                    │
│     Total Invalid Buildspecs:       3                                                                     │
│     Total Unique Tags:              15                                                                    │
│     Total Maintainers:              3                                                                     │
│                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

This would be similar to `buildtest report --row-count` but for `buildtest bc find`

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by jscook2345** [comment]
If you have a summary command, why do you want to add another command to do the same thing?

**Comment by shahzebsiddiqui** [comment]
Again for the same reason in https://github.com/buildtesters/buildtest/issues/1214#issuecomment-1295108471 the output of `buildtest bc summary` is quite long. 

Right now to get a count of unique tag names one needs to run something like this

```
 ~/gitrepos/buildtest/ [devel] buildtest bc find -t --terse -n | wc -l
32
```

Likewise an option like `buildtest bc find --tag-count` would be more accessible

**Comment by shahzebsiddiqui** [comment]
@prathmesh4321 after thinking through this task, i was thinking instead of creating separate options for getting different counts like tags, executors, number of buildspec we just have one option `buildtest bc find --row-count` that works similar to `buildtest report --row-count`.

**Comment by prathmesh4321** [comment]
> @prathmesh4321 after thinking through this task, i was thinking instead of creating separate options for getting different counts like tags, executors, number of buildspec we just have one option `buildtest bc find --row-count` that works similar to `buildtest report --row-count`.

@shahzebsiddiqui Makes sense. Do you want me to work on this issue ?

**Comment by shahzebsiddiqui** [comment]
Yeah that would be great. I think there are several output for `buildtest buildspec find` so any output that returns a table I think we can print the row count of the table. I hope that makes sense. 

If you want to take a shot at this that would be great.

**Comment by prathmesh4321** [comment]
> Yeah that would be great. I think there are several output for `buildtest buildspec find` so any output that returns a table I think we can print the row count of the table. I hope that makes sense.
> 
> If you want to take a shot at this that would be great.

@shahzebsiddiqui  Okay done.
