### ISSUE TITLE
Cannot find /usr/local/cpanminus/bin/cpanm

### ISSUE THREAD

**Issue by ZQyou** [buildtesters/buildtest#125]
The version I used:
```
$ git describe --tags
v0.7.2
```
The issue I ran into:
```
$ buildtest -h
sh: /usr/local/cpanminus/bin/cpanm: No such file or directory
sh: /usr/local/cpanminus/bin/cpanm: No such file or directory
/usr/local/lmod/lmod/modulefiles/Core directory does not exist specified in BUILDTEST_MODULEPATH
```

I did not have any problem using buildtest module few months ago.

**Comment by shahzebsiddiqui** [comment]
hi @ZQyou 
Does your system have Lmod.

Can you run ``rpm -q lmod``

Also can you give me output of ``echo $MODULEPATH``. It may be that if directory doesn't exist buildtest is exiting immediately because of invalid module tree.

**Comment by ZQyou** [comment]
Our system has  Lmod.
Here is the output of `$MODULEPATH`
```
/apps/lmodfiles/MPI/intel/18.0/mvapich2/2.3.2:/apps/lmodfiles/Compiler/intel/18.0:/apps/lmodfiles/Linux:/apps/lmodfiles/Core:/apps/lmod/lmod/modulefiles/Core
```

I tried:
```
$ BUILDTEST_MODULEPATH=/apps/lmodfiles/Core buildtest -h
sh: /usr/local/cpanminus/bin/cpanm: No such file or directory
sh: /usr/local/cpanminus/bin/cpanm: No such file or directory
/usr/local/lmod/lmod/modulefiles/Core directory does not exist specified in BUILDTEST_MODULEPATH
```
Do I need to have cpanm to use buildtest?

**Comment by shahzebsiddiqui** [comment]
Interesting I think i know the issue. The directory ``/apps/lmod/lmod/modulefiles/Core`` is suppose to mimic ``/usr/local/lmod/lmod/modulefiles/Core``. So to get around this issue you can do the following to add trees:

``buildtest module tree -a /apps/lmodFiles/Core``. The ``buildtest module tree`` will update ``BUILDTEST_MODULEPATH``. The variable ``BUILDTEST_MODULEPATH`` should be set to the root of module tree that would want set. By default it is reading ``MODULEPATH`` 

Please feel free to join slack if you want to chat.

**Comment by ZQyou** [comment]
It works after updating the configuration.
