### ISSUE TITLE
[FEATURE]: color output in terse mode for query options in 'buildtest buildspec find'   

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1254]
### Please describe your feature request

we should support coloring with terse output for any query options shown below

```
query:
  query options to retrieve from buildspec cache

  -b, --buildspec      Get all buildspec files from cache
  -e, --executors      get all unique executors from buildspecs
  --group-by-tags      Group tests by tag name
  --group-by-executor  Group tests by executor name
  -p, --paths          print all root buildspec paths
  -t, --tags           List all available tags

```

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by shahzebsiddiqui** [comment]
@JeffreyFG I have assigned this task to you, i can check back in 2 weeks if you feel this is too much we can reassign it. Ill try to limit assigned task to 1-2 max at any given time.

**Comment by prathmesh4321** [comment]
Hi @shahzebsiddiqui the above tasks are already completed via issue 1276 : https://github.com/buildtesters/buildtest/issues/1276. So we can close this issue.

![image](https://user-images.githubusercontent.com/35829130/201190380-46ab49bb-e6d0-4fd6-ace5-383594db8764.png)

![image](https://user-images.githubusercontent.com/35829130/201190564-558da0b3-6a74-4466-aa94-dcc9b3b16cb5.png)

![image](https://user-images.githubusercontent.com/35829130/201190889-4036ddd1-08b7-4cc4-9777-1f51d4f78728.png)

![image](https://user-images.githubusercontent.com/35829130/201191029-2603cc1a-5407-4917-b223-781d40044107.png)

![image](https://user-images.githubusercontent.com/35829130/201191203-130a8d16-3b10-41ed-a141-fdd8aeebd5e7.png)

**Comment by shahzebsiddiqui** [comment]
yep
