### ISSUE TITLE
support for environment-modules

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#128]
Once environment-modules has a json structure similar to ``spider -o spider-json $MODULEPATH``. buildtest can implement a parser to extract module information to do all the module operations.

See https://github.com/cea-hpc/modules/issues/303 for more details.

**Comment by vsoch** [comment]
@shahzebsiddiqui I think this belongs in the (other repository?) you are working on to just interact with modules. The more I learn and test, I think having lmod / modules in general as a hard requirement for the library severely limits it's usage.

**Comment by shahzebsiddiqui** [comment]
I am kinda thinking of closing this issue, unless their is a desire from user to support `environment-modules`.  The Module API features are specific to Lmod. Some features like user collection and Spider are specific to Lmod and not environment-modules. I added this as  a reminder but likely wont get to it since this requires major changes to ModuleAPI or even have API specific to each module system.

**Comment by vsoch** [comment]
I'm in support of that! I think the dependency on Lmod, if anything, needs to be somewhat lifted. If after all the work is done this is discussed as badly needed, then we can open a new issue.
