### ISSUE TITLE
Setup a gitlab runner for user bdtest on Perlmutter

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1302]
Let's setup a gitlab runner via user bdtest to run jobs on Perlmutter. 

- [ ] Install gitlab runner see https://docs.gitlab.com/runner/install/ and register token with https://software.nersc.gov/NERSC/buildtest
- [ ] Create a gitlab runner configuration file 
- [ ] Install Jacamar CI custom executor https://gitlab.com/ecp-ci/jacamar-ci 
- [ ] Start gitlab runner and tie it to a particular host. Take https://github.com/NERSC/spack-infrastructure/blob/main/restart-gitlab.sh as a starting point

**Comment by prathmesh4321** [comment]
Registering a runner using "gitlab-runner register" command is working and I can see the runner on gitlab under the runners section.
<img width="1413" alt="Screen Shot 2022-12-28 at 1 19 21 AM" src="https://user-images.githubusercontent.com/35829130/209782173-94a3f415-3c35-4b7d-91b4-f4de4eb685ff.png">

But when I try to run the runner using the "gitlab-runner run" command it gives the following error. I also tried resetting the registration token and rerun but that didn't work. 
<img width="1089" alt="Screen Shot 2022-12-28 at 1 19 57 AM" src="https://user-images.githubusercontent.com/35829130/209782660-55980cba-369d-4418-a2bb-95a19b44ea0a.png">

@shahzebsiddiqui Do you have any idea what could be the reason for the error ?

**Comment by shahzebsiddiqui** [comment]
closing this task now that we have a runner. Great job @prathmesh4321
