### ISSUE TITLE
[FEATURE]: option to exclude tags

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1437]
### Please describe your feature

Let's have an option in `buildtest build` to exclude by tags. We can already search by tags `buildtest bd -t tag1,tag2` which will discover buildspecs. We also have option to filter by tags `buildtest bd --filter tags=tag1` but there is no way to exclude tags.

For instance if one wants to build all tests in a directory and exclude all test by given tag name this is not possible at the moment.

### Suggest potential solution

Introduce a new option `buildtest bd -xt` with long option `--exclude-tags` that work similar to `-t` so you can exclude tags

Here are two ways this can be used. We can do comma separated list and also append this multiple times

```console
# comma separated
buildtest  bd -b /path/to/dir -xt cuda,mpi

buildtest bd -b example.yml -xt cuda -xt mpi
```

The exclusion will exclude any test that are found in list of tags if `tags` is empty or there is no match then test will be processed.

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by shahzebsiddiqui** [comment]
@prathmesh4321 @Xiangs18 let me know what you think about this feature.

**Comment by prathmesh4321** [comment]
> @prathmesh4321 @Xiangs18 let me know what you think about this feature.

@shahzebsiddiqui Yeah, exclude by tags will be a very useful feature. I think we should implement this.

**Comment by shahzebsiddiqui** [comment]
Ok cool, any suggestions on the option name, short and long option.
