### ISSUE TITLE
Add coverage for file_regex status check

### ISSUE THREAD

**Issue by prathmesh4321** [buildtesters/buildtest#1447]
### Please describe your feature

Add coverage for status check of `file_regex`. See https://app.codecov.io/gh/buildtesters/buildtest/blob/devel/buildtest/buildsystem/checks.py

![Screen Shot 2023-04-19 at 10 51 18 PM](https://user-images.githubusercontent.com/35829130/233270292-dd000727-67ed-4d7b-9efc-878efe050793.png)

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by shahzebsiddiqui** [comment]
@braeeast2001 i will be assigning this task to you

**Comment by shahzebsiddiqui** [comment]
can you please take a look at https://github.com/buildtesters/buildtest/blob/devel/tests/builders/test_builders.py file it has the tests for all the status checks

**Comment by shahzebsiddiqui** [comment]
this is the test for `file_regex` that we should use for the regression test. Simply create a symbolic link https://github.com/buildtesters/buildtest/blob/devel/tutorials/test_status/regex_on_filename.yml. The symlink are created for other files in the root of the directory https://github.com/buildtesters/buildtest/tree/devel/tests/builders for buildspecs that point to ones in the `tutorials` directory.
