### ISSUE TITLE
[DOCS]: No build output under Specifying Scheduler Directives section in Buildspec tutorial

### ISSUE THREAD

**Issue by Mendi03** [buildtesters/buildtest#1516]
### Documentation Link

https://buildtest.readthedocs.io/en/devel/buildspecs/spack.html#specifying-scheduler-directives

### Issue Description

The Specifying Scheduler Directives section under buildspec tutorial has a codeblock to show the output of the `buildtest inspect query` command; however, it is lacking a code block for the `buildtest build` command. This makes this section a bit unclear. 
![Screenshot 2023-07-05 at 10 45 42 AM](https://github.com/buildtesters/buildtest/assets/123998062/673b6a92-6610-496b-a194-03c67a0f3d31)

Note: This section is also missing some highlighting in the buildspec example.

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by shahzebsiddiqui** [comment]
@Mendi03 do you want to take on this task? Thanks for reporting this

**Comment by Mendi03** [comment]
No problem! I'll assign myself for this then
