### ISSUE TITLE
[DOCS]: -t instead of --testpath in query outputs of Buildspec Tutorial

### ISSUE THREAD

**Issue by Mendi03** [buildtesters/buildtest#1517]
### Documentation Link

https://buildtest.readthedocs.io/en/devel/buildspec_tutorial.html

### Issue Description

There are numerous instances in the Buildspec tutorial documentation where the inspect query output uses `-t` instead of `--testpath` but still shows the output for using testpath. 

This is an example found under [Setting environment variables](https://buildtest.readthedocs.io/en/devel/buildspecs/compiler.html#setting-environment-variables)
![Screenshot 2023-07-05 at 11 04 28 AM](https://github.com/buildtesters/buildtest/assets/123998062/317ae577-f595-4927-84b5-aa87b648206f)

And this is an example under [Create a Spack Environment by name](https://buildtest.readthedocs.io/en/devel/buildspecs/spack.html#create-a-spack-environment-by-name). In this case the command shows `--testpath` but the output shows that the command `-t` was used. But the codeblock shows the expected output of using `--testpath` still.

![Screenshot 2023-07-05 at 11 10 44 AM](https://github.com/buildtesters/buildtest/assets/123998062/935d4685-229f-4e04-bce6-098b8187b8ef)

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by shahzebsiddiqui** [comment]
Thanks for reporting this issue @Mendi03 do you want to fix this issue.

**Comment by Mendi03** [comment]
I will work on this issue once I finish the other 2 issues I am working on. In the meantime I'll leave it unassigned in case somebody else wants to take it.
