### ISSUE TITLE
Refactor for Python packaging install

### ISSUE THREAD

**Issue by vsoch** [buildtesters/buildtest#159]
The [instructions](https://buildtest.readthedocs.io/en/latest/installing_buildtest.html) specify to install the requirements.txt in docs:

```bash
$ pip install -r docs/requirements.txt
```
but this list is quite extensive - if we look at setup.py we certainly don't need sphinx (and other docs dependencies) to run the library.

```bash
       install_requires = [
            "argcomplete",
            "PyYAML",
        "buildtest-configs=="+BUILDTEST_VERSION,
	    "Python-buildtest-config=="+BUILDTEST_VERSION,
	    "Perl-buildtest-config=="+BUILDTEST_VERSION,
	    "Ruby-buildtest-config=="+BUILDTEST_VERSION,
	    "R-buildtest-config=="+BUILDTEST_VERSION,
       ]
```
What is the reason for directing the user to this file?

**Comment by vsoch** [comment]
It looks like there isn't instruction about the command `register-python-argcomplete`. The implication is that the user should know to follow the link to install something, but maybe this should be explicitly shown (it was confusing to me at first).

https://buildtest.readthedocs.io/en/latest/installing_buildtest.html#setting-up-auto-complete-on-buildtest-arguments

**Comment by vsoch** [comment]
If there aren't instructions for the user to install it, they will hit this error:

```bash
$ buildtest --help
Traceback (most recent call last):
  File "/share/software/user/open/python/3.6.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/share/software/user/open/python/3.6.1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/users/vsochat/SOFTWARE/buildtest-framework/buildtest/main.py", line 8, in <module>
    from buildtest.tools.menu import BuildTestParser
  File "/home/users/vsochat/SOFTWARE/buildtest-framework/buildtest/tools/menu.py", line 7, in <module>
    import argcomplete
ModuleNotFoundError: No module named 'argcomplete'
```
I'd suggest a separate requirements.txt to install actual required modules - I can PR this.

**Comment by shahzebsiddiqui** [comment]
Hi @vsoch,

please ignore the section found in setup.py i dont have a pip package for buildtest-framework anymore

```
  install_requires = [
            "argcomplete",
            "PyYAML",
        "buildtest-configs=="+BUILDTEST_VERSION,
	    "Python-buildtest-config=="+BUILDTEST_VERSION,
	    "Perl-buildtest-config=="+BUILDTEST_VERSION,
	    "Ruby-buildtest-config=="+BUILDTEST_VERSION,
	    "R-buildtest-config=="+BUILDTEST_VERSION,
       ]
```

Seems like `argcomplete` was not installed. Can you confirm you are using python3.6 or higher.

Yea in `master` branch you have to run `eval "$(register-python-argcomplete buildtest)"` after you are run the `sourceme.sh` The argcompletion is helpful for several buildtest commands.

**Comment by vsoch** [comment]
This would be helpful to be able to install to a specific python, instead of just using from the bin like spack. On our cluster the default python (which I forgot about) is 2.7.5. To use python3 I have to explicitly use python3.

**Comment by vsoch** [comment]
What are your reasons for not wanting a setup.py flow? Just to keep everything served from the repo? And if the setup.py isn't needed, should it be removed?

**Comment by shahzebsiddiqui** [comment]
oh i just didnt get time to package up buildtest-framework into a pip package. I had this done initially and didnt both removing it thinking i would do it some point. I think it was bit more overhead during release since project was still beta release

**Comment by vsoch** [comment]
ah okay, makes sense!

**Comment by shahzebsiddiqui** [comment]
seems like you have may have both system python for python 2 and 3. I generally have a software stack that includes Anaconda3.

I use pipenv https://github.com/pypa/pipenv to setup my environment. I didnt specify the full details on how to setup virtualenv or pipenv its user preference personally. 

I highly recommend pipenv to get the python3 environment its much easier but thats your call.

**Comment by vsoch** [comment]
That's what I do locally too - but I'm mimicking a user that would want to shell into a cluster and install this. They are going to do the minimum number of steps - meaning likely they could run into this issue.

**Comment by shahzebsiddiqui** [comment]
yea I know definitely the setup part for buildtest can be greatly improved. There is not much other than setting up PATH, installing pip deps and setting up argcomplete

**Comment by vsoch** [comment]
I can work on these things! Let's move to slack.

**Comment by shahzebsiddiqui** [comment]
Is this issue still relevant? considering my recent PR #160

**Comment by vsoch** [comment]
Let me change the title so it's relevant to something I'll add to my PR - python packaging.

**Comment by vsoch** [comment]
This is all done! I don't think there will be a release soon - there are more changes warranted before that, but we can close the issue here. @shahzebsiddiqui do you want help to manage the packages on pypi? I have an account [here](https://pypi.org/user/vsochat/).
