### ISSUE TITLE
[DOCS]: need to add documentation for extract line numbers in metrics

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1744]
### Documentation Link

https://buildtest.readthedocs.io/en/devel/writing_buildspecs/metrics.html

### Issue Description

@Xiangs18 can you please add docs for this PR https://github.com/buildtesters/buildtest/issues/1725 

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by Xiangs18** [comment]
Should I start a new section in [Docs](https://buildtest.readthedocs.io/en/devel/writing_buildspecs/metrics.html)? 
I assume file_regex would required some documentation as well?

**Comment by shahzebsiddiqui** [comment]
> Docs

Yes just add this as a new subsection after https://buildtest.readthedocs.io/en/devel/writing_buildspecs/metrics.html#metrics-with-regex-type-via-re. You can have one section for extracting line number and use both `file_regex` and `regex`. If you look at the content of this page, we already cover `file_regex` in the example so its not required to just have a section to explain what `file_regex` is. This is already covered in the page. I just want you to document how one can extract a particular line using the `linenum` property.
