### ISSUE TITLE
Semi-Automate CHANGELOG for release

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#178]
Writing a CHANGELOG after every release can be very time consuming. Looking at few options in marketplace I'd want to try out NextRelease.io https://github.com/marketplace/nextrelease-io

Just doing a quick search on changelog there are 15+ options https://github.com/marketplace?utf8=%E2%9C%93&query=changelog

**Comment by vsoch** [comment]
@shahzebsiddiqui I want to suggest that while the project is so young / broken that we focus on making it better instead of these things that (arguably) I would label as over-engineering.

**Comment by shahzebsiddiqui** [comment]
@vsoch definitely. I agree, i am putting on TODO list so i don't forget. It may be we end up doing this manually. I briefly tried NextRelease.io but didnt have time to deep dive.

**Comment by vsoch** [comment]
I haven't tried many of these tools, but I'd also be down to learn something new. Worst case, it's too much and we do the manual approach, which I find helpful to do as a sanity check after making changes anyway.
