### ISSUE TITLE
Documentation section for concepts

### ISSUE THREAD

**Issue by vsoch** [buildtesters/buildtest#190]
I think it would be good to add additional concepts to documentation, to make it clear to the user what ModuleCommand / collections map to, in terms of the Lmod software! My original thought:

> have a documentation page that briefly overviews some high-level concepts and has links for more detail.

And then some descriptions to get us started in this comment https://github.com/HPC-buildtest/buildtest-framework/issues/188#issuecomment-591220430.

**Comment by shahzebsiddiqui** [comment]
This task is complete. I will add separate page describing the ModuleAPI. As per buildtest and module terminology it is available in ``index.html``
