### ISSUE TITLE
Dependency Discussion: termcolor

### ISSUE THREAD

**Issue by vsoch** [buildtesters/buildtest#206]
Where is termcolor used? I don't see it outside of the setup files, is it a dependency we can remove?

```
setup.py:        "termcolor==1.1.0",
buildtest_framework.egg-info/requires.txt:termcolor==1.1.0
docs/requirements.txt:termcolor==1.1.0
```

**Comment by vsoch** [comment]
Also, I want to bring up `argcomplete` - it's a sort of "nice to have" but I don't think it's essential for the library. When I tested out autocompletion on sherlock it wasn't speedy enough to make it worth it for me.

**Comment by shahzebsiddiqui** [comment]
Yes `termcolor` can be removed. It was part of the module integration https://github.com/HPC-buildtest/buildtest-framework/blob/master/buildtest/tools/modules.py#L16 this is now removed in devel. It was used for color coding output of ``buildtest module list``.

I agree `argcomplete` can be removed also.

**Comment by vsoch** [comment]
Gotcha! I'll do both of these.

**Comment by shahzebsiddiqui** [comment]
issue resolved closing now
