### ISSUE TITLE
Remove buildtest show schema

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#215]
The purpose of ``buildtest show schema`` was to show YAML schema on CLI with all the key and description. Since this is being developed and documented in https://github.com/HPC-buildtest/schemas we can remove the feature for now.

I think in future we can add the cli feature to show schema that could take the ``json`` schema and all the YAML examples and print them to screen. Another option could be to have all the schema docs on a GitHub page and use the CLI to pull the page locally. It could be like a man page style. 

I can see the feature useful if designed like a man page which would help users that are developing a test to view docs and examples from command line instead of going to a separate web-page. If this is to work, all the docs should be in the schema repo or some GitHub page so that the framework is not re-implementing the schema docs.

**Comment by vsoch** [comment]
This will be very easy to do once the schema script module is added - it will be trivial to load a recipe config based on any specific type, validate it, and then print to the console.

**Comment by vsoch** [comment]
This is refactored with the new structure - you can either show the global schema:

```
 buildtest show -c
BUILDTEST_MODULEPATH                               = 
EDITOR                                             = vim
build[testdir]                                     = /home/vanessa/.buildtest/testdir
build[module][purge]                               = {'force': False}
```

Or a schema for a specific type (e.g script)

```
$ buildtest show schema --name script
{
    "$id": "https://HPC-buildtest.github.io/schemas/script/script-v0.0.1.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "BuildTest Test Configuration for Script",
    "type": "object",
    "required": [
        "type",
        "run"
    ],
    "propertyNames": {
        "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
    },
    "properties": {
        "type": {
            "type": "string",
            "pattern": "^script$"
        },
        "description": {
            "type": "string",
            "description": "A description for the build recipe."
        },
        "maintainers": {
            "type": "array",
            "description": "One or more maintainers or aliases",
            "minItems": 1,
            "items": {
                "type": "string"
            }
        },
        "env": {
            "type": "object",
            "description": "One or more key value pairs for an environment (key=value)",
            "minItems": 1,
            "items": {
                "type": "object",
                "minItems": 1,
                "propertyNames": {
                    "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
                }
            }
        },
        "shell": {
            "type": "string",
            "default": "bash",
            "description": "The shell interpreter to use."
        },
        "pre_run": {
            "type": "string",
            "description": "A script run before the default run using the default shell."
        },
        "run": {
            "type": "string",
            "description": "A script to run using the default shell."
        },
        "post_run": {
            "type": "string",
            "description": "A script run after the default run using the default shell."
        }
    }
}
```
@shahzebsiddiqui it sounds like you also wanted to support just printing a yaml schema (e.g., the slurm-hello.yml) to the screen? Is this really useful when the user could just cat / open a file with an editor? If the functionality isn't proven needed, for now I'd suggest we close this issue, and readdress when someone says "I want to be able to show my schema with a command."

**Comment by shahzebsiddiqui** [comment]
@vsoch  the printing of YAML file ``slurm-hello.yml`` was part of ``buildtest build --dry`` it showed content of YAML during the build. It was also available ``buildtest testconfigs view <testconfig>`` see https://buildtest.readthedocs.io/en/latest/managing_testconfigs.html. I personally dont think it's useful right now to show a YAML file. Also note that ``buildtest testconfigs`` is removed in ``devel`` so not to worry. 

In regards to schema file ``buildtest show schema``, i think it could be useful to have this in CLI. It is equivalent to easyblock keys https://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html#available-easyconfig-parameters

The only thing is yea, user can just ``cat`` the file, i just kinda wished there was a nice tabular way to show all the keys along with description. I can see myself using this command to review schema keys to check all keys when writing test. It helps me to get details of schema instead of going to another page to read the schema docs or cat some obscure path.

I guess the scope of this issue  does not apply since #219 added this support and i am fine with the way it is, unless you disagree or have better way.

**Comment by shahzebsiddiqui** [comment]
This issue is irrelevant now closing this ticket
