### ISSUE TITLE
Define a standard directory structure for Regression Tests

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#216]
Currently, there is no standard in place for writing regression tests. At the moment, the regtest in https://github.com/HPC-buildtest/buildtest-framework/tree/master/tests are mostly unit test. I propose the directory structure for unit tests map to the file name in the following way.

To test for source file ``buildtest/exceptions.py`` there should be a test ``tests/test_exceptions.py``. This makes it easy to associate the regression test with each source file and allows new users to easy contribute back and troubleshoot regression test.

Each sub-directory in ``buildtest`` can be mapped to ``tests`` so a file ``buildtest/utils/file.py`` should have a test ``tests/utils/test_file.py``. We should also document some best practice on how to start writing regression tests and contribute back. It should be this page https://buildtest.readthedocs.io/en/devel/contributing/regression_testing.html. It may not be clear to folks new to pytest that all tests start with ``test_<name>.py`` we should document this.

It may be worth mentioning if we decide on a standard for testing classes. Right now if there is a class ``BuildTestCommand`` there is a class ``TestBuildTestCommand`` which will test the class. So name of class is ``Test<className>``. 

For all methods, there is no standard naming scheme yet, but a simple scheme could be simple as ``test_<method-name>``. This may not work for all cases since some methods may need multiple tests so having meaningful names would be required.

**Comment by vsoch** [comment]
Great job @shahzebsiddiqui !
