### ISSUE TITLE
Standard for docstrings

### ISSUE THREAD

**Issue by vsoch** [buildtesters/buildtest#220]
There currently isn't a standard (or a way to check that all is correct) for dostrings and we need to add this. My previous comment in #219 

@shahzebsiddiqui I agree on having a standard for docstrings, and:

 1. it should be handled in a separate PR
 2. it should be enforced with a tool, for example URL checker used this. https://app.codacy.com/gh/urlstechie/URLs-checker/pullRequest?prid=5180802

So for now, albeit they are imperfect, I'll open up an issue to discuss this further and then a separate PR down the line to add the integration and address the changes it requests.

**Comment by vsoch** [comment]
Also see comment https://github.com/HPC-buildtest/buildtest-framework/pull/219#pullrequestreview-374852034. I believe the tool I linked handles spacing, capitalization, and periods.

**Comment by shahzebsiddiqui** [comment]
@vsoch This https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html would be good place to start looking at how to format parameters in docstring

**Comment by shahzebsiddiqui** [comment]
Here are few examples for some docstring standards

Google Style Docstring: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
Numpy Docstrings: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy
Sphinx docstring: https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

For now we are using Sphinx docstring format, i personally think its a bit too verbose as pose to Google Style. I think if we make a change to another format, we need to see how this affects the API docs: https://buildtest.readthedocs.io/en/devel/py-modindex.html

I don't like Numpy docstring format either so i'd be in favor of Google Style over the Sphinx format. If the API docs look good in Google Style then i would be in favor of a more concise docstring. Not sure what is more popular in the community, whats your thoughts @vsoch ?
