### ISSUE TITLE
missing magic string in test script

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#227]
Test needs to have magic string ``#!/bin/bash`` or ``#!/bin/csh``. This is important specify when it comes to using modules in Lmod see https://lmod.readthedocs.io/en/latest/040_FAQ.html. 

Here is an example generated file

```
cd $TESTDIR
FILE=1mb_bzip2.txt
TARFILE=1mb_bzip2.txt.bz2
dd if=/dev/zero of=$FILE bs=1M count=1
tar cvjf $TARFILE $FILE
ll $TARFILE
bzip2 -d $TARFILE
```

**Comment by vsoch** [comment]
Haha, I've never heard "magic string" - I think this is called the shebang, or bang line. See https://bash.cyberciti.biz/guide/Shebang.

**Comment by vsoch** [comment]
This would easily be parsed from the `executable` variable derived from the command, since it looks for the full path of a shell. The command could be modified to do the parsing (and get this executable) in a separate function so that it can be run without executing the command. I can do this later this week if you like.

**Comment by shahzebsiddiqui** [comment]
I must have heard this "magic string" from one of the instructor videos I took. Yes shebang is it.

I was going to do it tomorrow, but if you have started then I can wait. I also want to get rid of cd TESTDIR. 

That doesn't work and there is no such variable.

**Comment by vsoch** [comment]
I wouldn't get rid of cd TESTDIR, that will be needed. What will change is what exactly TESTDIR is, it likely will be derived custom based on the relative path of the file to .buildtest. If TESTDIR isn't there it's because the environment exports are missing.

**Comment by shahzebsiddiqui** [comment]
if it's okay let me work on this, i won't remove the TESTDIR for time being.

**Comment by vsoch** [comment]
You'll need to update the BuildTestCommand to extract some executable (the full path) based on a shell, and then use that full path for the shabang. What we cannot do is take a shell preference and assume /usr/local/bin or /usr/bin, etc.

**Comment by vsoch** [comment]
We've addressed this, closing.
