### ISSUE TITLE
Remove ML Bot

### ISSUE THREAD

**Issue by vsoch** [buildtesters/buildtest#238]
This doesn't seem like a useful service, it's an excessive / extra bot that I think we should remove until there is warranted evidence that it is needed. https://mlbot.net/data/HPC-buildtest/buildtest-framework

**Comment by shahzebsiddiqui** [comment]
I removed Issue Label Bot from the org. This was me trying out few integration. I agree doesn't make sense to have it.

**Comment by vsoch** [comment]
Ah okay, it's still in the docs, so I think we should keep this issue open until it's removed from there (it triggered an error with urlchecker).

**Comment by vsoch** [comment]
This is now removed! Closing.
