### ISSUE TITLE
Add stages for executor

### ISSUE THREAD

**Issue by vsoch** [buildtesters/buildtest#240]
As discussed in https://github.com/HPC-buildtest/buildtest-framework/pull/237#issuecomment-604514513, an executor should have different stages to interact with a builder (and execute some build). I like @shahzebsiddiqui suggestion for a start:

> I like this idea, it makes sense to me and defines a proper control sequence of events run by each executor.

For slurm i could see the stages such as 
- setup: buildtest will write slurm job scripts
- check: check if slurm partition is available for accepting jobs, if not skip job 
- dispatch:  dispatch jobs to scheduler
- poll: wait for jobs to finish, periodically run ``squeue`` or ``sacct`` to see if job is in one of its end state see https://slurm.schedmd.com/squeue.html#lbAG
- gather: gather all job data, exit code, output and error to print to stdout and store data for post-processing (convert output to json)
- close: clean up any generated files

**Comment by shahzebsiddiqui** [comment]
This is now addressed in https://github.com/buildtesters/buildtest/pull/329
