### ISSUE TITLE
Provide a set of valid and invalid configuration files for regression testing

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#254]
Currently we don't have distinction between valid and invalid files, all the files are in ``tests/config_schema_examples`` we can introduce ``valid`` and ``invalid`` sub-directories to store valid and invalid configuration files for testing purposes. This allows for proper organization on where to store configuration examples and write tests for intended purpose. Both valid and invalid tests need to be written to ensure json schema is working properly.

```
config_schema_examples/
   invalid/
   valid/
      local-example.yml
      slurm-example.yml
```

**Comment by shahzebsiddiqui** [comment]
@vsoch I already provided a set of valid configs and there is a directory structure but there are no invalid scripts. I think we can go crazy with all sorts of invalid config.

Is this even the right approach? Should we still keep this issue open?

**Comment by vsoch** [comment]
I think it would be logical to think of common cases that would be considered invalid that we'd really want to catch, like spelling errors for important keys, or adding an extra key. If we define that small set of cases, e.g.,

 - adding an option that isn't known
 - not having an option that is required
 - a spelling mistake for an important key

that should limit to possibly just three invalid tests.

**Comment by shahzebsiddiqui** [comment]
Makes sense for first point **adding an option that isn't known** that the issue described in https://github.com/HPC-buildtest/buildtest-framework/issues/253 
I think jsonschema should catch ``required`` section in the validate section

A spelling mistake for a key would be an unknown key, either it would be an unknown option or ignored depending if ``additionalProperties`` is set. Anyhow i dont know of how many edge cases we may have it may only be a few. I guess we can address this with ticket https://github.com/HPC-buildtest/buildtest-framework/issues/253 at same time.
