### ISSUE TITLE
decide what to do with restore config option (buildtest config restore) or add a save option

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#259]
Currently, we have option to restore site configuration from backup file, this is via ``buildtest config restore``

The first time, buildtest is issued, it will copy the default configuration to ``settings.yml`` and ``settings.yml.bak`` which are duplicate files. User can  make change to site configuration and this may mean ``settings.yml`` can diverge from original file.

Currently, i dont see a use-case of restore from backup, since i can just delete the file and buildtest will copy it.

Another option would be to have a mechanism to save site configuration something like (``buildtest config save``) which will save the site configuration by making a backup copy. Then user can make change as needed and if they screw up, then can restore the file via ``buildtest config restore``. This only makes sense from command line perspective.

If it doesn't make sense to have ``save`` feature we can just remove the ``restore`` operation

**Comment by vsoch** [comment]
I would delete the "bak" file, I don't see how this does much but be confusing. When a config restore is done, just copy from the install location. Buildtest is _not_ a library for version control of user settings, if they want version control, they can put a .git repository there :)

**Comment by vsoch** [comment]
Instead of restore, possibly call it reset?

**Comment by shahzebsiddiqui** [comment]
Makes sense I think reset sounds good and I don't like having the .bak file we can reset from default file we provide. I'll fix this
