### ISSUE TITLE
Issue with BuildTestCommand poll, output and error not returning

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#263]
There is an issue with logic on how BuildTestCommand is implemented. In particular I have seen that the condition shown below is reached asap and ouptut and error stream is not captured since returncode is not None hence it breaks from while loop.

https://github.com/HPC-buildtest/buildtest-framework/blob/abcfad94b69598f87f15c58e3c0f0762d9c9a99f/buildtest/utils/command.py#L63

For example when running ``buildtest build -c examples/script/python-circle.yml`` i see the return code is 0 when troubleshooting and the output and error stream is not captured.

the output file is empty as shown below

```
gitpod /workspace/buildtest-framework $ ll -l /workspace/buildtest-framework/.buildtest/python-circle/run/circle_area_04-05-2020-19-22.out
-rw-r--r-- 1 gitpod gitpod 0 Apr  5 19:22 /workspace/buildtest-framework/.buildtest/python-circle/run/circle_area_04-05-2020-19-22.out
```

The expected output of this test should be the following

```
gitpod /workspace/buildtest-framework $ python .buildtest/python-circle/circle_area.py 
Circle Radius  2
Area of circle  12.566370614359172
Block
```

This is not captured in the test output file.

**Comment by shahzebsiddiqui** [comment]
@vsoch i was hoping you can look into this as it's core to execution shell commands in buildtest.

**Comment by vsoch** [comment]
Will do! I have a lot on my plate right now, but it's on my list.
