### ISSUE TITLE
better way to handle source files during test execution

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#273]
@vsoch Currently we don't have a good way to specify path to source file for simple compilation. Since buildtest will write testscript in a new directory, buildtest has no knowledge of and supporting files to be copied over. For example this simple vector addition openacc example has to be written like this in order for it to work

see https://github.com/HPC-buildtest/buildtest-stampede2/blob/master/tests/apps/openacc/vecadd.yml
```
version: 0.0.1

vecadd_gnu:
  type: script
  description: Vector Addition example with GNU compiler
  env:
    cc: gcc
    cflags: -fopenacc
    ldflags: -lm
    exe: vecAdd
    srcdir: /work/06908/sms1990/stampede2/buildtest-stampede2/tests/apps/openacc/src
  run: |
    module load gcc
    $cc $cflags -o $exe $srcdir/vecAdd.c $ldflags
    ./$exe
```

The ``srcdir`` is where vecAdd.c resides so that testscript can reference full path to file. If we were to copy all files or create symlinks we could just reference file like ``src/vecAdd.c``. This assumes we are writing test with assumption that current working directory is where buildspec resides. This avoids hard-coded paths

This is the generated testscript

```
(buildtest-framework) login4.stampede2(1023)$ cat .buildtest/vecadd/vecadd_gnu.sh
#!/bin/bash
cc=gcc
cflags=-fopenacc
ldflags=-lm
exe=vecAdd
srcdir=/work/06908/sms1990/stampede2/buildtest-stampede2/tests/apps/openacc/src
module load gcc
$cc $cflags -o $exe $srcdir/vecAdd.c $ldflags
./$exe
```

I think we can use symlink to the files in actual directory. In this case we don't really know what files or directory to symlink since we don't have a standard directory structure to enforce. For example it's good practice to separate source files from buildspecs to avoid cluttering the current directory so that's when i propose a subdirectory ``src``.  This where user can place source files. User may have headers and data files but maybe we can include ``include`` and ``data`` sub-directory in future. I guess for time being we can use ``src`` as a directory structure where buildtest can symlink.

I am in the vecdd test directory and here is the content of the directory.

```
(buildtest-framework) login4.stampede2(1029)$ pwd
/work/06908/sms1990/stampede2/buildtest-stampede2/.buildtest/vecadd
(buildtest-framework) login4.stampede2(1030)$ ll -l
total 24
drwx------ 2 sms1990 G-817668  4096 Apr 13 10:46 run
-rwx------ 1 sms1990 G-817668 13912 Apr 13 10:46 vecAdd
-rwxr-xr-x 1 sms1990 G-817668   208 Apr 13 10:46 vecadd_gnu.sh
```

I propose a symlink as follows

```
(buildtest-framework) login4.stampede2(1032)$ ln -s /work/06908/sms1990/stampede2/buildtest-stampede2/tests/apps/openacc/src src
(buildtest-framework) login4.stampede2(1033)$ ll -l
total 28
drwx------ 2 sms1990 G-817668  4096 Apr 13 10:46 run
lrwxrwxrwx 1 sms1990 G-817668    72 Apr 13 10:55 src -> /work/06908/sms1990/stampede2/buildtest-stampede2/tests/apps/openacc/src
-rwx------ 1 sms1990 G-817668 13912 Apr 13 10:46 vecAdd
-rwxr-xr-x 1 sms1990 G-817668   208 Apr 13 10:46 vecadd_gnu.sh
```

This way i can update the script to reference ``src`` as i would be writing the script. Note in this example i don't need to create an environment ``srcdir`` 

```
(buildtest-framework) login4.stampede2(1036)$ cat vecadd_gnu.sh
#!/bin/bash
cc=gcc
cflags=-fopenacc
ldflags=-lm
exe=vecAdd
srcdir=src
module load gcc
$cc $cflags -o $exe $srcdir/vecAdd.c $ldflags
./$exe
```

Now this runs as same as before
```
(buildtest-framework) login4.stampede2(1035)$ sh vecadd_gnu.sh

Lmod is automatically replacing "intel/18.0.2" with "gcc/7.1.0".


Inactive Modules:
  1) libfabric

The following have been reloaded with a version change:
  1) impi/18.0.2 => impi/17.0.3     2) python3/3.7.0 => python3/3.6.1

final result: 1.000000
```

If we decide to go ahead with this approach we need buildtest to create symlinks as part of test creation if ``src`` is found in directory where buildspec is located. This would avoid having hardcoded path in script.

**Comment by vsoch** [comment]
I think we should by default use all relative paths, with the path being relative to the working directory of the build spec file. I'm not sure if we should enforce using some kind of src directory or not - on the one hand it makes it easy to know what files are "included" for a build, on the other hand, It should be up to the user if he/she wants to create a `src` (or not) and possibly buildtest should not enforce some hard coded structure to get a test to work. 

Here is how I think this should work:

 - working directory defaults to where buildtest config file is, or a custom path with --workdir. TLDR: this is where the .buildtest folder is generated with output, results, etc.
 - if this workdir relative path is honored, we shouldn't need to mess around with symlinks or copying files. We can os.chdir() to the working directory before the run.

So -1 to symlinks, -1 to requiring a src directory. The user should be able to run tests with the files provided, derived from the original source, and only the final build / output artifacts are saved in .buildtest in the working directory.

**Comment by shahzebsiddiqui** [comment]
I am having hard time following what will be the working directory. Can you provide an example build with path to working directory, test directory and maybe how you would write the buildspec

**Comment by vsoch** [comment]
The working directory is the dirname of the buildspec. The buildspec (and associated files) would be written relative to it.

**Comment by shahzebsiddiqui** [comment]
So here is my setup at stampede2 with the example above. My working directory is root of **buildtest-stampede2** repo 

```
(buildtest-framework) login4.stampede2(998)$ pwd
/work/06908/sms1990/stampede2/buildtest-stampede2
(buildtest-framework) login4.stampede2(999)$ buildtest build -b tests/apps/openacc/vecadd.yml

            Discovered Buildspecs

/work/06908/sms1990/stampede2/buildtest-stampede2/tests/apps/openacc/vecadd.yml



Buildspec Name                 SubTest                        Status                         Buildspec Path
________________________________________________________________________________________________________________________
vecadd                         vecadd_gnu                     PASSED                         /work/06908/sms1990/stampede2/buildtest-stampede2/tests/apps/openacc/vecadd.yml


============================================================
                        Test summary
============================================================
Executed 1 tests
Passed Tests: 1/1 Percentage: 100.000%
Failed Tests: 0/1 Percentage: 0.000%
```

```
(buildtest-framework) login4.stampede2(1000)$ tree .buildtest/
.buildtest/
└── vecadd
    ├── run
    │   ├── vecadd_gnu_04-15-2020-10-43.err
    │   └── vecadd_gnu_04-15-2020-10-43.out
    ├── vecAdd
    └── vecadd_gnu.sh

2 directories, 4 files
```

The content of the test is the following, note my ``src`` directory is basically ``PWD/tests/apps/openacc/src`` where i have the source file

```
(buildtest-framework) login4.stampede2(1002)$ tree $PWD/tests/apps/openacc/src
/work/06908/sms1990/stampede2/buildtest-stampede2/tests/apps/openacc/src
└── vecAdd.c

0 directories, 1 file

(buildtest-framework) login4.stampede2(1001)$ cat .buildtest/vecadd/vecadd_gnu.sh
#!/bin/bash
cc=gcc
cflags=-fopenacc
ldflags=-lm
exe=vecAdd
srcdir=/work/06908/sms1990/stampede2/buildtest-stampede2/tests/apps/openacc/src
module load gcc
$cc $cflags -o $exe $srcdir/vecAdd.c $ldflags
./$exe

```

I am not following how we can reference script without some hardcoded path.

Note in https://github.com/HPC-buildtest/buildtest-stampede2/blob/master/tests/apps/openacc/vecadd.yml#L11 i specify ``srcdir`` relative to environment variable ``$WORK`` which is predefined for all users. I anticipate myself to use the path root of ``buildtest-stampede2`` repo in several tests, should we allow user to specify this in buildtest settings file so its declared once.

I'd not want to use $PWD defined in Buildspec since test would fail depending on where i invoke the command.  I dont think there is a way to invoke a Python command in YAML something like ``os.path.dirname(os.path.abspath(__file__))`` and assign it to a variable in YAML. 

Also i find myself declaring a variable multiple times in each test block in a single Buildspec to reference a file. For example see https://github.com/HPC-buildtest/buildtest-stampede2/blob/master/tests/apps/mkl/sgemm.yml

I think there should be some concept of global variable declaration in buildtest settings or some other means that can be referenced in the ``run`` section by some means. The way i see it could work is it would be a shell variable that is added into the test script

**Comment by vsoch** [comment]
I think you are overthinking it. We take the dirname of /work/06908/sms1990/stampede2/buildtest-stampede2/tests/apps/openacc/vecadd.yml, which is openacc, and that's the working directory that everything is run relative to. So if you have files in source, you reference them as src/file. And if you have some environment variable like $WORK with a full path, there is no reason that shouldn't work too. And if you specify for buildtest to have a different --workdir, that would be honored instead. 

For the user, the easiest thing is to think relatively to their testing file, simple as that. The more advanced user will use some custom --workdir.

**Comment by shahzebsiddiqui** [comment]
I have tried referencing file relative to Buildspec and run code from current directory. I think if you try it will make more sense, it's because the relative directory is in relation to where testscript is written which causes path to not be found. 

I updated tutorials  repo https://github.com/HPC-buildtest/tutorials   with some examples and this can be run if you set an environment $WORK to parent directory where you cloned ``tutorials``. 

Then you can run all the tests in ``apps`` and ``system`` 

```

(buildtest-framework) ssi29@ag-mxg-hulk090> echo $WORK
/u/users/ssi29/gpfs
(buildtest-framework) ssi29@ag-mxg-hulk090> pwd
/u/users/ssi29/gpfs/tutorials

(buildtest-framework) ssi29@ag-mxg-hulk090> buildtest build -b apps -b system

            Discovered Buildspecs

/mxg-hpc/users/ssi29/tutorials/system/ulimits.yml
/mxg-hpc/users/ssi29/tutorials/apps/openmp/matrixmux/matrixmux.c.yml
/mxg-hpc/users/ssi29/tutorials/apps/openacc/vecadd.yml
/mxg-hpc/users/ssi29/tutorials/apps/compression/bzip2.yml
/mxg-hpc/users/ssi29/tutorials/system/selinux.yml
/mxg-hpc/users/ssi29/tutorials/apps/compression/zlib.yml
/mxg-hpc/users/ssi29/tutorials/apps/serial/hello.yml
/mxg-hpc/users/ssi29/tutorials/system/disk_usage.yml
/mxg-hpc/users/ssi29/tutorials/system/systemd.yml
/mxg-hpc/users/ssi29/tutorials/apps/openmp/helloworld/omp_hello.c.yml



Buildspec Name                 SubTest                        Status                         Buildspec Path
________________________________________________________________________________________________________________________
ulimits                        ulimit_filelock                PASSED                         /mxg-hpc/users/ssi29/tutorials/system/ulimits.yml
ulimits                        ulimit_cputime                 PASSED                         /mxg-hpc/users/ssi29/tutorials/system/ulimits.yml
ulimits                        ulimit_stacksize               FAILED                         /mxg-hpc/users/ssi29/tutorials/system/ulimits.yml
matrixmux.c                    matrixmux_openmp               PASSED                         /mxg-hpc/users/ssi29/tutorials/apps/openmp/matrixmux/matrixmux.c.yml
vecadd                         vecadd_gnu                     PASSED                         /mxg-hpc/users/ssi29/tutorials/apps/openacc/vecadd.yml
bzip2                          bzip_compression               PASSED                         /mxg-hpc/users/ssi29/tutorials/apps/compression/bzip2.yml
selinux                        selinux_disable                PASSED                         /mxg-hpc/users/ssi29/tutorials/system/selinux.yml
zlib                           zlib_compression               PASSED                         /mxg-hpc/users/ssi29/tutorials/apps/compression/zlib.yml
zlib                           zlib_decompress                PASSED                         /mxg-hpc/users/ssi29/tutorials/apps/compression/zlib.yml
hello                          fortan_hello                   PASSED                         /mxg-hpc/users/ssi29/tutorials/apps/serial/hello.yml
hello                          c_hello                        PASSED                         /mxg-hpc/users/ssi29/tutorials/apps/serial/hello.yml
hello                          cplusplus_hello                PASSED                         /mxg-hpc/users/ssi29/tutorials/apps/serial/hello.yml
disk_usage                     root_disk_usage                PASSED                         /mxg-hpc/users/ssi29/tutorials/system/disk_usage.yml
systemd                        systemd_default_target         PASSED                         /mxg-hpc/users/ssi29/tutorials/system/systemd.yml
omp_hello.c                    hello_world                    PASSED                         /mxg-hpc/users/ssi29/tutorials/apps/openmp/helloworld/omp_hello.c.yml


============================================================
                        Test summary
============================================================
Executed 15 tests
Passed Tests: 14/15 Percentage: 93.333%
Failed Tests: 1/15 Percentage: 6.667%
```

For now i have set an environment variable ``srcdir`` that get's the right path to source file

```
(buildtest-framework) ssi29@ag-mxg-hulk090> grep -iR -E "^srcdir*" .
./.buildtest/matrixmux.c/matrixmux_openmp.sh:srcdir=$WORK/tutorials/apps/openmp/matrixmux/src
./.buildtest/vecadd/vecadd_gnu.sh:srcdir=$WORK/tutorials/apps/openacc/src
./.buildtest/hello/fortan_hello.sh:srcdir=$WORK/tutorials/apps/serial/src
./.buildtest/hello/cplusplus_hello.sh:srcdir=$WORK/tutorials/apps/serial/src
./.buildtest/hello/c_hello.sh:srcdir=$WORK/tutorials/apps/serial/src
./.buildtest/omp_hello.c/hello_world.sh:srcdir=$WORK/tutorials/apps/openmp/helloworld/src

```

Anyhow I think what i was looking for is the ability to declare variable globally that could be shared across Buildspecs instead of declaring them using ``env`` in each Buildspec.

My first thought was to declare them in settings file using ``vars`` you declare global variables and they automatically get added into all scripts for time being.

```
vars:
  WORK: /u/users/ssi29/gpfs
```

Then you can reference them in ``run`` section as you normally write a test. The ``vars`` could be used to declare any variable that could be shared across multiple tests. For example, you may have several singularity tests in a Buildspec that leverages use of environment variable https://sylabs.io/guides/3.5/user-guide/build_env.html#library to tweak singularity  and it may be beneficial to declare it once in a settings file instead of declaring it in every Buildspec.
