### ISSUE TITLE
All the silver bullets for testing :)

### ISSUE THREAD

**Issue by fgeorgatos** [buildtesters/buildtest#28]
Ideas from other testing frameworks implementation:

* ref. https://bitbucket.org/michilu/shell-doctest
  * Labels (inside docstrings, nice)
  * Test per host case (think GROMACS against a 1 or 2-socket affinity, 4-gpu server)
* ref. https://github.com/brodie/cram
  * supporting different shells and contexts
  * Initialize variables
  * interactive training of tests

**Comment by shahzebsiddiqui** [comment]
@fgeorgatos i am going to close this issue since it was created in 2017. Definitely let's stay in touch in Slack and feel free to open a new issue.

**Comment by fgeorgatos** [comment]
sure - they were only supplied as interesting implementations to shop ideas from.
