### ISSUE TITLE
HPC-buildtest organization name change

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#280]
We should change the name of the buildtest organization currently located at https://github.com/HPC-buildtest

The namespace ``buildtest`` and ``buildtests`` is taken https://github.com/buildtest https://github.com/buildtests so we must think of a new name.

Preferably, we should have a name that matches these requirements
- Short org name (max 10chars) currently ``buildtest`` is 9 chars
- Name should be unique so that there is no conflict between another open source project 
- The name should be available on pypi https://pypi.org/ so we could distribute package 
- Single word only, no special characters or dashes allowed (``build-test``)

Let's share few ideas on names here and proceed from here.

**Comment by vsoch** [comment]
Hmm, so I was originally thinking these are for the organization name (and not the package, which is already buildtest, no?) So here are a few suggestions for the organization

 - buildorg
 - buildoc  (akin to "build doctor" but also alludes to documentation

But if you want the org name to == the project (and repository name) and the pypi name this is more challenging. Are you suggesting that you are open to changing the name of the package entirely? That would give us a lot more options:

 - https://github.com/buildshares

One of the fundamental ideas for the project is the idea of sharing builds. The buildshare project (pip install buildshare) would be under the buildshares org on GitHub (buildshare is taken). E.g., this repo would be https://github.com/buildshares/buildshare (or actually it could still be https://github.com/buildshares/buildtest) 

https://github.com/buildsteps

I sort of like this one - the idea of many buildsteps coming together into a full build is kind of cool. Then you could have https://github.com/buildsteps/buildtest still (are you not able to get buildtest on pypi?)

https://github.com/buildspec

Since we have these build spec things, you could also just call it that :) The library is based on creating, sharing, running, and testing build specs, so it's not so crazy. It would nicely tie the namespace together I think too - buildspec would be common knowledge for the spec files and the software.

https://github.com/buildspec

I can think of others too... let me know!

**Comment by vsoch** [comment]
My 0.02 is that I like the last (buildspec) the most. It's available as an org, and a package on pypi. https://pypi.org/project/buildspec/

**Comment by shahzebsiddiqui** [comment]
So my thoughts are to change **buildtest-framework** to **buildtest**. Id prefer not to change the name of the project this may imply change to the module names and a complete rewrite of all the docs and some or if not most GitHub integration links.

I don't think there is an issue with getting buildtest namespace in pypi https://pypi.org/search/?q=buildtest  so we should not have an issue as soon as we do a release, we should also distribute on pypi.

So I think we can name the org whatever we want and not worry about few of the requirements especially changing the project to match org. I also send two of the guys email again to see if they respond back. I tried googling these guys they don't exist on this planet :) I really wish they can respond back and delete the buildtest project so we can take the namespace.

I like Buildspec for what it represents a YAML file, so I'd not want to confuse that with an org.

**Comment by shahzebsiddiqui** [comment]
If you want to wait and see if we get response from these guys and maybe we can take the buildtest namespace maybe if you give a 2 weeks. 

I guess a question I have is will we refer to the project by the org or by the name buildtest. Keep in mind two different names would cause a bit of confusion and given the history I have with previous talks and publication it be best if name is still buildtest. if it's last resort I am leaning towards we can call it **buildtesters**. If the namespace buildtest is freed up we could think about taking this namespace.

**Comment by vsoch** [comment]
It’s customary to name by the project, not the org. You see a lot of projects under different (and even changing) org names.

**Comment by shahzebsiddiqui** [comment]
In that case, i'd rather be safe and we can change ``buildtest-framework`` --> ``buildtest`` for this repo. Initially i had a repo ``buildtest`` which served only the docs but then i merge the docs into the framework.  

If you agree this change could be done immediately, and then we would need to change all the update all the links, hopefully the url-checker will come in handy now.

As per org, the one that comes to mind is ``buildtesters``, it contains the word buildtest, but also implies that users a.k.a ``testers`` who use buildtest are called ``buildtesters``.

**Comment by vsoch** [comment]
+1, I would rename the repo to buildtest right away, and try to claim the namespace on pypi (you can add me, I'm vsochat). We can manage the org name after - buildtesters I guess would work but it feels long.

**Comment by vsoch** [comment]
You could do a take on "metoo" and call it "buildtoo" :)

**Comment by vsoch** [comment]
Like buildtool but with a silent l?

**Comment by shahzebsiddiqui** [comment]
I changed this repo name, to ``buildtest``, The names sound nice ``buildtool`` i think the org name should have some variation of ``buildtest`` so that we have a high page rank. Doing a quick search on google now with ``buildtest`` we have 6 top-pages belonging to this page. 

Here are few suggestions, can you please sort names based on your preference. I believe all these names are available.

- buildtesters
- buildntest ( sound like 'building' 'test') 
- buildtesters
- buildstest - i wouldn't bother pronounce the 's' but to get the namespace, trying saying this 10x really fast :)
- buildztest

**Comment by vsoch** [comment]
I think `buildstest` would be confusing because people would confuse the org name with the package name. `buildtesters` is clear, but it's longer than the others. (you put it twice in the list, are you trying to bias me? lol). My favorite is `buildntest` because to me it sounds like `build and test` and that's exactly what is being done.

As for my favorites? I don't think any of them are super great, but in that they are all better than HPC-buildtest, it's an improvement. I don't think the github organization name determines page rank, the page rank algorithm has to do with linking and clicks. The organization name associated is irrelevant.

**Comment by shahzebsiddiqui** [comment]
I also really like buildntest let's go with this. Yes it's much better than what we have right now 😁.

**Comment by vsoch** [comment]
Want to let it sit a bit (the org name) before making global changes? To make sure we like it (and in case we think of something better?) It's a big (permanent) change after the fact so we should be sure. I'm not sure I like it. We could be more creative too, e.g.,

 - https://github.com/buildforge
 - https://github.com/buildmod
 - https://github.com/buildmake
 - https://github.com/buildsteps
 - https://github.com/buildlad
 - https://github.com/buildum
 - https://github.com/buildat (like "build that')

**Comment by vsoch** [comment]
I like most of these better than buildntest, because of the length factor.

**Comment by shahzebsiddiqui** [comment]
+1 for buildsteps, buildforge. So just to be clear, the logo #282 will be for ``buildtest`` and not for org name since we can't get https://github/com/buildtest. The ones you suggested can have slightly different meaning and we could go creative with logos but if we decide to have the name ``buildtest`` in the logo then it can cause some confusion between org name and the project. Also keep in mind, we also have https://github.com/buildntest/lmodule which belongs to buildtest for now. 

It won't be an issue if we picked an org as close to ``buildtest``. I think the two that i like are 
- https://github.com/buildtesters
- https://github.com/buildntest

**Comment by vsoch** [comment]
Yep, clear on the logo, I'm just talking about the name for the org.

You don't like any of the other suggestions I made? I can keep thinking...

 - https://github.com/buildlib
 - https://github.com/building (is this one really available, or just protected?)
 - https://github.com/testguild
 - https://github.com/buildest (a descriptor like "biggest" but to describe building, "buildest") also is similar to buildtest (but shorter).
 - https://github.com/allbuild

I think I might like buildtesters better, but I don't love it. I guess after setting it to buildntest, it looks weird.

**Comment by vsoch** [comment]
More ideas...

 - https://github.com/buildbee (could be really cute org logo)
 - https://github.com/testit 
 - https://github.com/collatest (collaborative test)
 - https://github.com/testivity
 - https://github.com/buildix (akin to unix, linux, etc.)
 - https://github.com/buildology
 - https://github.com/testology
 - https://github.com/buildzilla
 - https://github.com/buildalus
 - https://github.com/buildvue
 - https://github.com/mcbuild
 - https://github.com/buildsuite

**Comment by shahzebsiddiqui** [comment]
Based on all i saw i like 
- https://github.com/buildsteps
- https://github.com/buildoc
- https://github.com/buildat (this sounds cools too)
-  https://github.com/buildest (this is interesting, but i guess it doesn't matter how we pronounce it.)
- https://github.com/buildsuite this is good too. I used the word ``testsuite`` a while back for some features in buildtest

Here is one other thought what about

- https://github.com/buildtestcom - this represents buildtest + "community" which is a collection of buildtest repos, and it may include a collection of buildtest repos for each HPC site. Right now i have ``buildtest-stampede2`` in this org for time being but it doesn't seem like it's the right place. I do want each site to have their own repo but a central location where we can find all the tests. 

The name also applies that it is a buildtest community.

**Comment by vsoch** [comment]
The last one sounds WAY too much like zombocom, which would just make it a joke. And I wouldn't think "community" I would think ".com" which makes me think of a dated point in time when .com's were all the rage :)

If we choose based on length then buildat and buildoc and buildest would be the top three? But the other ones are good too - I like all of them better than buildntest, which I think looks weird because d and n don't really appear next to one another often in the English language. if you want to think more (or come up with more ideas around community, group, lab, etc.) then I can give feedback on another set. I definitely gave my fair share of ideas for today so I think I'm spent!

**Comment by vsoch** [comment]
Just kidding a few more... these are based on community but I don’t like them as much :/

https://github.com/buildgrp
https://github.com/buildbunch
https://github.com/buildfam
https://github.com/buildfact
https://github.com/buildlot
https://github.com/buildsec
https://github.com/buildpeople 
https://github.com/buildfolks
https://github.com/buildclan

buildcommunity is taken.

**Comment by vsoch** [comment]
https://github.com/buildmart
https://github.com/testmart
https://github.com/buildsh (You could try for build.sh)
https://github.com/buildcmd
https://github.com/testrope
https://github.com/buildcollective
https://github.com/buildcoop
https://github.com/buildville
https://github.com/buildset

**Comment by shahzebsiddiqui** [comment]
Thanks for the suggestion, i dont like much of the suggestions based on the community so i am in agreement with you. 

I guess we can ditch ``buildtestcom`` it may seem weird, i figured it may also sound like the ``.com`` era and i also thought about this.

The ones that stuck out to me that were my favorite are the following two

1. https://github.com/buildsteps - 
  **Pros:** 
    - Character length 10 chars, it's same char count as ``buildntest`` but name is grammatically correct 
    - Logo: i can see a good logo with this using a series of stairs or steps. A simple design could be a 10 steps with a letter per step that spells out ``buildtest``
   **Cons:**
      - Doesn't have the name ``buildtest`` in name, and it may not be clear if ``buildsteps`` means anything in relation to buildtest

2. https://github.com/buildtesters - 
 **Pros:**
  - Includes the name ``buildtest``, also implies users are called ``buildtesters``
  - Shortest and most meaningful namespace that includes ``buildtest`` in the name
 **Cons:**
   - Char length 12 chars vs 10 chars (buildntest)

**Comment by vsoch** [comment]
I agree, and I like the two that you've narrowed it down to. We can actually edit the html on the page to "preview" how it would be:

![image](https://user-images.githubusercontent.com/814322/79695913-b8e3c080-8236-11ea-92df-46ef01d1e869.png)

and

![image](https://user-images.githubusercontent.com/814322/79695923-cb5dfa00-8236-11ea-8d77-41b9e27c7126.png)

I think I like buildsteps better. It implies modular, and also has a nice visual for a logo, and usually something with "steps" make me think "easy" or "clear." I think we could call the org buildsteps and still have a community of "buildtesters."

**Comment by vsoch** [comment]
You didn't like testit? it's very short.

**Comment by shahzebsiddiqui** [comment]
> You didn't like testit? it's very short.

Not really. Sorry

**Comment by shahzebsiddiqui** [comment]
> I agree, and I like the two that you've narrowed it down to. We can actually edit the html on the page to "preview" how it would be:
> 
> ![image](https://user-images.githubusercontent.com/814322/79695913-b8e3c080-8236-11ea-92df-46ef01d1e869.png)
> 
> and
> 
> ![image](https://user-images.githubusercontent.com/814322/79695923-cb5dfa00-8236-11ea-8d77-41b9e27c7126.png)
> 
> I think I like buildsteps better. It implies modular, and also has a nice visual for a logo, and usually something with "steps" make me think "easy" or "clear." I think we could call the org buildsteps and still have a community of "buildtesters."

This looks nice, it's bit tough decision, i am kinda leaning more towards **buildtesters** but i like both names. So here were my thoughts based on the two names

**buildtester**

1. I can see _buildtesters_ term to refer to **buildtest users**  and not just be any arbitrary name for sake of getting a namespace. 
2. I could see a documentation where we can have **buildtesters** grouped by **sites** so that we have a point of contact for any buildtester who wants to contact someone to use a test from one of the test repositories.
3. We are free to make logo whatever we want, but the name ``buildsteps`` seem to be more catchy when coming with a logo.
4. We could also refer to each buildtest test repo (buildtest-stampede2) as a ``buildtesters`` org. I am not sure what the best way to get all buildtest test repo in one org while giving them anyone privilege to create a repo but not have admin access to other repos. It would be nice if all buildtest test repos are in one central location at-least this builds a community of test repos. Another solution would be to create an empty repo and have everyone fork and use that to start as basis for the test repo. We won't expect contribution back but atleast all user can navigate to any fork to access other folks test. Ultimately, buildtest was meant for community sharing of tests so i could see this being useful if ``buildtesters`` was used as an org to host the test repos independent of this current org. I am not sure the best route.
5. Lastly i had this silly idea of having a leaderboard of all tests that buildtesters could vote. This was a bit tricky but i had  thought about this idea described in wiki but i dont know how useful it would be https://github.com/buildntest/buildtest/wiki/Managing-a-Test-Repository#voting-on-test

**Buildsteps** 
1. I can see a nice logo since the name is visual with steps
2. I see a good motto maybe **Build a Test one buildstep at a time**  
3. Name is shorter as pose to **buildtesters**
4. Currently, i dont see how we could refer to ``buildsteps`` in context of buildtest, as pose to ``buildtesters`` i can see some context w.r.t documentation

**Comment by vsoch** [comment]
Sounds like you are decided :)

**Comment by shahzebsiddiqui** [comment]
Well not really sure about point 4. I didn't like ``buildtesters`` in the beginning i was think i would be copying easybuilders https://github.com/easybuilders/ so i didnt want to do that. Anyhow, if we have a solution to point 4 not sure if we need a separate org for hosting tests since I am not sure where to place ``buildtest-stampede2``. Soon i will create a repo when i start testing Cori at LBNL.

**Comment by vsoch** [comment]
I think the "copy" actually is a positive thing, it copies something that has worked, and you might only worry if the easybuild team would have issue (I really doubt it!). I would try to just host them in the same org, having a second is excessive.

**Comment by shahzebsiddiqui** [comment]
Since we are out of luck on http://github.com/buildtest and user has not replied despite several email attempts i'd prefer ``buildtesters`` over ``buildsteps`` so that the name has some relevance. I wish there would be more input from users but atm the project is relatively new so slack community is pretty much dead until we get new release.

We would need some logo #282  the one that came to mind was one was the word ``buildsteps`` with a stairs spelling out "buildtest". I think we need more logo designs. Maybe a catchy motto? 

Here are some thoughts 

- Be a Buildtester, use buildtest
- build, test, be a Buildtester
- Test your HPC with a Buildtester
- Hire a Buildtester to test your HPC! <-- this is my favorite

**Comment by vsoch** [comment]
lol I don't think a "motto" is necessary at this point. Maybe when there is a larger community you could open this up and have a vote. For now, just focus on the org name.

**Comment by shahzebsiddiqui** [comment]
Makes sense to me.

**Comment by shahzebsiddiqui** [comment]
Okay i will change the org name to ``buildtesters`` for now and in future we can try to get some input when there is a community. I still wished we have http://github.com/buildtest but it wasn't meant to be.
