### ISSUE TITLE
resurrect buildtest build report

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#284]
In ``devel`` we removed ``buildtest build report`` and it's reporting features that are still present in ``master`` branch. See https://buildtest.readthedocs.io/en/latest/build_subcommand/build_status.html#build-report-buildtest-build-report for details.

We first need to capture every build and metadata associated to Buildspec and produced output, error, log file into a json file. Maybe we have one json file per build or have one json file for all builds. Once we have the data captured, we should have a command line option to retrieve each build or test id.

**Comment by vsoch** [comment]
I think the output structure, and lock file functionality needs to be developed before this. You can look at snakemake source code if you need ideas.

**Comment by vsoch** [comment]
I can’t find the thread now because I have like 1000 emails from you, but for the shebang is there any reason that we can’t always use /usr/bin/env followed by whatever shall they choose? And then of course honor that for the actual execution?

**Comment by shahzebsiddiqui** [comment]
This is now resolved with `buildtest report` https://github.com/buildtesters/buildtest/pull/322
