### ISSUE TITLE
Similar library: commander

### ISSUE THREAD

**Issue by vsoch** [buildtesters/buildtest#301]
Just for your FYI / inspiration @shahzebsiddiqui, there is a similar library that runs build testing (or general script testing) via a yaml schema, see https://github.com/SimonBaeumer/commander.

**Comment by vsoch** [comment]
Feel free to close this issue after you've perused.

**Comment by shahzebsiddiqui** [comment]
Thanks for sharing @vsoch it is very interesting, i like the different mechanism for checking test result. This would be what the ``status`` key is doing but we only providing an expression. This  could be enhanced to provide different search capability.

The node concept is similar to the ssh executor i had in mind that i wanted to implement soon.
