### ISSUE TITLE
License template update

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#577]
Based on our discussion @vsoch 

The license file may need an update, I have reached out to IPO@lbl.gov for response, the MIT license from timemory https://raw.githubusercontent.com/NERSC/timemory/develop/LICENSE resembles MIT content but differs in the title.  

```
Copyright (c) 2019, The Regents of the University of California, 
through Lawrence Berkeley National Laboratory (subject to receipt of any 
required approvals from the U.S. Dept. of Energy).  All rights reserved.
```

The rest of the text matches what is provided by MIT license see https://opensource.org/licenses/MIT

**Comment by vsoch** [comment]
You can usually put multiple headers. Take a look at the older Singularity licenses when Greg was still at LBNL.
