### ISSUE TITLE
add CODEOWNERS

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#614]
@adityakavalur: I am thinking of using this as added security into who can modify CI files.

see https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

We should add codeowners to manage who can change gitlab CI files in https://github.com/buildtesters/buildtest/tree/devel/.gitlab. We dont want arbitrary user changing the workflow expecting the PRs to trigger this action. We can limit this to few users only.

We need to see if gitlab CODEOWNERS https://docs.gitlab.com/ee/user/project/code_owners.html  behave similar to github CODEOWNERS or they are slightly different

It's not clear how github and gitlab will map usernames and not sure if these codeowners will need to be part of gitlab or github. If they are part of gitlab i would add this in `.gitlab/` directory to differentiate this. I suspect the usernames will be different between OLCF and NERSC which can cause some weird issues. This will require testing with and without codeowners and see how pipeline behaves.

**Comment by adityakavalur** [comment]
I think this a decent approach for the facility folk to be responsible for their yaml files. As for mapping username across instances, I do not think there is an inherent way to do this in Github/Gitlab. Ideally both of these UI's should have an aliases field in the setting that can be used to map username+domain address. However, there is no such thing. Any translations will have to be maintained by buildtest.

**Comment by shahzebsiddiqui** [comment]
i am now thinking it may not be good idea to implement CODEOWNER and it doesn't get us much gain. I think having pipelines set to manual is fine, they can't run the pipeline even if they make change which prevents user from running arbitrary code. This only applies to users that have push access to upstream repo to trigger pipeline. That being said, i think we shouldn't proceed.
