### ISSUE TITLE
Concurrent jobs/test limit for a executor type

### ISSUE THREAD

**Issue by adityakavalur** [buildtesters/buildtest#715]
It seems like buildtest runs all the jobs that it validates, in parallel. While a high number of concurrent jobs is not an issue if jobs are being submitted to a scheduler, this can be problematic for shell executors, as facility login nodes are generally a shared resource. It would be useful to have a user variable on the executor level that can control the number of concurrent jobs that can run for that particular executor type.

**Comment by shahzebsiddiqui** [comment]
I checked the current implementation of LocalExecutor and its not concurrent. Each test is run sequentially so first, we need buildtest to run concurrently before we limit concurrency. So for now this issue is not relevant
