### ISSUE TITLE
[DOCS]: update doc about before/after_script 

### ISSUE THREAD

**Issue by jgphpc** [buildtesters/buildtest#946]
### Documentation Link

https://buildtest.readthedocs.io/en/latest/configuring_buildtest/overview.html#before-script-for-executors

### Issue Description

I could not find any issue about this (apart from https://github.com/buildtesters/buildtest/issues/470 maybe).
The text below should have `before_script.sh` instead of `after_script.sh`

> This can be found in var/executors directory as shown below
```
var/executors/
|-- local.bash
|   |-- after_script.sh
```

When I add `after_script: ` in my config, I get: 
```
  error = <ValidationError: "Additional properties are not allowed ('after_script' was unexpected)">
```

+ in https://buildtest.readthedocs.io/en/latest/configuring_buildtest/overview.html#default-configuration
I see:
`cat: /buildtest/settings/config.yml: No such file or directory`

I guess that's not the expected output.

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by jgphpc** [comment]
Fixed in https://buildtest.readthedocs.io/en/devel/configuring_buildtest/overview.html#before-script-for-executors

**Comment by shahzebsiddiqui** [comment]
@jgphpc thanks for bringing this up. The after_script used to exist but was removed and this was an error in docs that never got cleaned up. I'll fix this

**Comment by shahzebsiddiqui** [comment]
i have addressed this now in https://github.com/buildtesters/buildtest/pull/949
