### ISSUE TITLE
[DOCS]: 'buildtest config summary' is invalid

### ISSUE THREAD

**Issue by jgphpc** [buildtesters/buildtest#947]
### Documentation Link

https://buildtest.readthedocs.io/en/latest/configuring_buildtest/command_line_interface.html#configuration-summary

### Issue Description

> buildtest config summary
```
usage: buildtest [options] [COMMANDS] config [-h]  ...
buildtest [options] [COMMANDS] config: error: argument : invalid choice: 'summary' (choose from 'compilers', 'edit', 'executors', 'systems', 'validate', 'view')
```

> buildtest -V
```
buildtest version 0.11.0
```

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by jgphpc** [comment]
Fixed in https://buildtest.readthedocs.io/en/devel/features.html#command-line-interface-to-buildtest-configuration

**Comment by shahzebsiddiqui** [comment]
Yes `buildtest config summary` was removed
