### ISSUE TITLE
change buildtest License 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#99]
buildtest is Licensed as GPLv3 https://github.com/HPC-buildtest/buildtest-framework/blob/master/LICENSE this is probably not the best option. Need to change the license asap.

**Comment by fgeorgatos** [comment]
MIT and Apache license tend to be the most broad choices after struggling with GPLx - effectively you choose without or with patent provisioning. If you choose MIT, it’s easy to later switch to whatever, while the reverse is only possible from, say, BSD.

**Comment by shahzebsiddiqui** [comment]
I am also leaning towards MIT which makes most sense. I am also discussing this with other members in the community and internally with my employer.

**Comment by shahzebsiddiqui** [comment]
closing this issue. Changed the license to MIT.
